export const Emoji = {
    'Angry Face with Horns': require('@/assets/emoji/ver01/Angry Face with Horns.png'),
    'Angry Face': require('@/assets/emoji/ver01/Angry Face.png'),
    'Anguished Face': require('@/assets/emoji/ver01/Anguished Face.png'),
    'Anxious Face with Sweat': require('@/assets/emoji/ver01/Anxious Face with Sweat.png'),
    'Astonished Face': require('@/assets/emoji/ver01/Astonished Face.png'),
    'Beaming Face with Smiling Eyes-1': require('@/assets/emoji/ver01/Beaming Face with Smiling Eyes-1.png'),
    'Beaming Face with Smiling Eyes': require('@/assets/emoji/ver01/Beaming Face with Smiling Eyes.png'),
    'Clown Face': require('@/assets/emoji/ver01/Clown Face.png'),
    'Cold Face': require('@/assets/emoji/ver01/Cold Face.png'),
    'Confounded Face': require('@/assets/emoji/ver01/Confounded Face.png'),
    'Confused Face': require('@/assets/emoji/ver01/Confused Face.png'),
    'Cowboy Hat Face': require('@/assets/emoji/ver01/Cowboy Hat Face.png'),
    'Crying Face': require('@/assets/emoji/ver01/Crying Face.png'),
    'Disappointed Face': require('@/assets/emoji/ver01/Disappointed Face.png'),
    'Disguised Face': require('@/assets/emoji/ver01/Disguised Face.png'),
    'Dizzy Face': require('@/assets/emoji/ver01/Dizzy Face.png'),
    'Downcast Face with Sweat': require('@/assets/emoji/ver01/Downcast Face with Sweat.png'),
    'Drooling Face': require('@/assets/emoji/ver01/Drooling Face.png'),
    'Exploding Head': require('@/assets/emoji/ver01/Exploding Head.png'),
    'Expressionless Face': require('@/assets/emoji/ver01/Expressionless Face.png'),
    'Face Blowing a Kiss': require('@/assets/emoji/ver01/Face Blowing a Kiss.png'),
    'Face Exhaling': require('@/assets/emoji/ver01/Face Exhaling.png'),
    'Face in Clouds': require('@/assets/emoji/ver01/Face in Clouds.png'),
    'Face Savoring Food': require('@/assets/emoji/ver01/Face Savoring Food.png'),
    'Face Screaming in Fear': require('@/assets/emoji/ver01/Face Screaming in Fear.png'),
    'Face Vomiting': require('@/assets/emoji/ver01/Face Vomiting.png'),
    'Face with Hand Over Mouth': require('@/assets/emoji/ver01/Face with Hand Over Mouth.png'),
    'Face with Head-Bandage': require('@/assets/emoji/ver01/Face with Head-Bandage.png'),
    'Face with Medical Mask': require('@/assets/emoji/ver01/Face with Medical Mask.png'),
    'Face with Monocle': require('@/assets/emoji/ver01/Face with Monocle.png'),
    'Face with Open Mouth': require('@/assets/emoji/ver01/Face with Open Mouth.png'),
    'Face with Rolling Eyes': require('@/assets/emoji/ver01/Face with Rolling Eyes.png'),
    'Face with Spiral Eyes': require('@/assets/emoji/ver01/Face with Spiral Eyes.png'),
    'Face with Steam From Nose': require('@/assets/emoji/ver01/Face with Steam From Nose.png'),
    'Face with Symbols on Mouth': require('@/assets/emoji/ver01/Face with Symbols on Mouth.png'),
    'Face with Tears of Joy': require('@/assets/emoji/ver01/Face with Tears of Joy.png'),
    'Face with Thermometer': require('@/assets/emoji/ver01/Face with Thermometer.png'),
    'Face with Tongue-1': require('@/assets/emoji/ver01/Face with Tongue-1.png'),
    'Face with Tongue': require('@/assets/emoji/ver01/Face with Tongue.png'),
    'Face Without Mouth': require('@/assets/emoji/ver01/Face Without Mouth.png'),
    'Fearful Face': require('@/assets/emoji/ver01/Fearful Face.png'),
    'Flushed Face': require('@/assets/emoji/ver01/Flushed Face.png'),
    'Frowning Face with Open Mouth': require('@/assets/emoji/ver01/Frowning Face with Open Mouth.png'),
    'Frowning Face': require('@/assets/emoji/ver01/Frowning Face.png'),
    'Grinning Face with Big Eyes': require('@/assets/emoji/ver01/Grinning Face with Big Eyes.png'),
    'Grinning Face with Smiling Eyes': require('@/assets/emoji/ver01/Grinning Face with Smiling Eyes.png'),
    'Grinning Face with Sweat': require('@/assets/emoji/ver01/Grinning Face with Sweat.png'),
    'Grinning Face': require('@/assets/emoji/ver01/Grinning Face.png'),
    'Grinning Squinting Face': require('@/assets/emoji/ver01/Grinning Squinting Face.png'),
    'Hot Face': require('@/assets/emoji/ver01/Hot Face.png'),
    'Hugging Face': require('@/assets/emoji/ver01/Hugging Face.png'),
    'Kissing Face with Closed Eyes': require('@/assets/emoji/ver01/Kissing Face with Closed Eyes.png'),
    'Kissing Face with Smiling Eyes': require('@/assets/emoji/ver01/Kissing Face with Smiling Eyes.png'),
    'Kissing Face': require('@/assets/emoji/ver01/Kissing Face.png'),
    'Lying Face': require('@/assets/emoji/ver01/Lying Face.png'),
    'Money-Mouth Face': require('@/assets/emoji/ver01/Money-Mouth Face.png'),
    'Nauseated Face': require('@/assets/emoji/ver01/Nauseated Face.png'),
    'Nerd Face': require('@/assets/emoji/ver01/Nerd Face.png'),
    'Neutral Face': require('@/assets/emoji/ver01/Neutral Face.png'),
    'Partying Face': require('@/assets/emoji/ver01/Partying Face.png'),
    'Pensive Face': require('@/assets/emoji/ver01/Pensive Face.png'),
    'Persevering Face': require('@/assets/emoji/ver01/Persevering Face.png'),
    'Pleading Face': require('@/assets/emoji/ver01/Pleading Face.png'),
    'Pouting Face': require('@/assets/emoji/ver01/Pouting Face.png'),
    'Relieved Face': require('@/assets/emoji/ver01/Relieved Face.png'),
    'Rolling on the Floor Laughing': require('@/assets/emoji/ver01/Rolling on the Floor Laughing.png'),
    'Sad but Relieved Face': require('@/assets/emoji/ver01/Sad but Relieved Face.png'),
    'Shushing Face': require('@/assets/emoji/ver01/Shushing Face.png'),
    'Sleeping Face': require('@/assets/emoji/ver01/Sleeping Face.png'),
    'Sleepy Face': require('@/assets/emoji/ver01/Sleepy Face.png'),
    'Slightly Frowning Face': require('@/assets/emoji/ver01/Slightly Frowning Face.png'),
    'Slightly Smiling Face': require('@/assets/emoji/ver01/Slightly Smiling Face.png'),
    'Smiling Face with Halo': require('@/assets/emoji/ver01/Smiling Face with Halo.png'),
    'Smiling Face with Heart-Eyes': require('@/assets/emoji/ver01/Smiling Face with Heart-Eyes.png'),
    'Smiling Face with Hearts': require('@/assets/emoji/ver01/Smiling Face with Hearts.png'),
    'Smiling Face with Horns': require('@/assets/emoji/ver01/Smiling Face with Horns.png'),
    'Smiling Face with Smiling Eyes-1': require('@/assets/emoji/ver01/Smiling Face with Smiling Eyes-1.png'),
    'Smiling Face with Smiling Eyes': require('@/assets/emoji/ver01/Smiling Face with Smiling Eyes.png'),
    'Smiling Face with Sunglasses': require('@/assets/emoji/ver01/Smiling Face with Sunglasses.png'),
    'Smiling Face with Tear': require('@/assets/emoji/ver01/Smiling Face with Tear.png'),
    'Smirking Face': require('@/assets/emoji/ver01/Smirking Face.png'),
    'Sneezing Face': require('@/assets/emoji/ver01/Sneezing Face.png'),
    'Star-Struck': require('@/assets/emoji/ver01/Star-Struck.png'),
    'Thinking Face-1': require('@/assets/emoji/ver01/Thinking Face-1.png'),
    'Thinking Face': require('@/assets/emoji/ver01/Thinking Face.png'),
    'Tired Face': require('@/assets/emoji/ver01/Tired Face.png'),
    'Unamused Face': require('@/assets/emoji/ver01/Unamused Face.png'),
    'Upside-Down Face': require('@/assets/emoji/ver01/Upside-Down Face.png'),
    'Weary Face': require('@/assets/emoji/ver01/Weary Face.png'),
    'Winking Face with Tongue': require('@/assets/emoji/ver01/Winking Face with Tongue.png'),
    'Winking Face': require('@/assets/emoji/ver01/Winking Face.png'),
    'Woozy Face': require('@/assets/emoji/ver01/Woozy Face.png'),
    'Worried Face': require('@/assets/emoji/ver01/Worried Face.png'),
    'Yawning Face': require('@/assets/emoji/ver01/Yawning Face.png'),
    'Zany Face': require('@/assets/emoji/ver01/Zany Face.png'),
    'Zipper-Mouth Face': require('@/assets/emoji/ver01/Zipper-Mouth Face.png'),
};
